//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adperfilmenu
    {
        public int ciPerfilmenu { get; set; }
        public int ciMenu { get; set; }
        public int ciPerfil { get; set; }
        public Nullable<bool> bdConsultar { get; set; }
        public Nullable<bool> bdGuardar { get; set; }
        public string ciEstado { get; set; }
        public string ciUsuarioIngreso { get; set; }
        public System.DateTime fcIngreso { get; set; }
        public string ciUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> fcModificacion { get; set; }
    }
}
