//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adusuarios
    {
        public int idUsuario { get; set; }
        public string ciUsuario { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string txNombreCorto { get; set; }
        public string txDescripcion { get; set; }
        public string txClave { get; set; }
        public string ciEstado { get; set; }
        public Nullable<bool> bdMaster { get; set; }
        public string ciUsuarioIngreso { get; set; }
        public System.DateTime fcIngreso { get; set; }
        public string ciUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> fcModificacion { get; set; }
        public string txDirectorioImagen { get; set; }
    }
}
