//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adusuarioafiliado
    {
        public int ciUsuarioAfiliado { get; set; }
        public string ciUsuario { get; set; }
        public Nullable<int> IdAfiliado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    }
}
