//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        public int RegAnuncioId { get; set; }
        public Nullable<int> RegId { get; set; }
        public string RegCodigoUnico { get; set; }
        public string RegAnuncioPalabraClave { get; set; }
        public string RegAnuncioAcercaDe { get; set; }
        public string RegAnuncioEstado { get; set; }
        public Nullable<System.DateTime> RegAnuncioFecha { get; set; }
        public Nullable<int> AnioAnuncioReg { get; set; }
        public Nullable<int> MesAnuncioReg { get; set; }
        public Nullable<int> DiaAnuncioReg { get; set; }
        public Nullable<int> AnioAnuncioHastaId { get; set; }
        public Nullable<int> MesAnuncioHastaId { get; set; }
        public Nullable<int> DiaAnuncioHastaId { get; set; }
        public string RegRutaImagen1 { get; set; }
        public string RegRutaImagen2 { get; set; }
        public string RegRutaImagen3 { get; set; }
        public string Titulo { get; set; }
    }
}
