//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int IdPersona { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> TipoIdentificacion { get; set; }
        public string RazonSocial { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombresCompletos { get; set; }
        public Nullable<System.DateTime> fcNacimiento { get; set; }
        public Nullable<int> cianios { get; set; }
        public Nullable<System.DateTime> fcIngreso { get; set; }
        public string ciUsuarioIngreso { get; set; }
        public Nullable<System.DateTime> fcModificacion { get; set; }
        public string ciUsuarioModifica { get; set; }
        public string ciEstado { get; set; }
        public Nullable<int> ciLocalidad { get; set; }
        public string txDireccion { get; set; }
        public string txTelefono { get; set; }
        public string txCodConadis { get; set; }
        public string txCorreoElectronico { get; set; }
        public Nullable<int> ciTipoPersona { get; set; }
    }
}
