//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int RegProductId { get; set; }
        public Nullable<int> RegPerfilId { get; set; }
        public Nullable<int> RegId { get; set; }
        public string RegCodigoUnico { get; set; }
        public string RegRutaImagen { get; set; }
        public byte[] RegStreamImagen { get; set; }
        public string RegTituloProducto { get; set; }
        public string RegDescripcionProducto { get; set; }
        public string RegPreciProducto { get; set; }
        public Nullable<System.DateTime> RegFecha { get; set; }
        public Nullable<int> AnioReg { get; set; }
        public Nullable<int> MesReg { get; set; }
        public Nullable<int> DiaReg { get; set; }
        public Nullable<int> IsNew { get; set; }
    }
}
