//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuncioImages
    {
        public int RegAnuncioImagenId { get; set; }
        public Nullable<int> RegAnuncioId { get; set; }
        public Nullable<int> RegId { get; set; }
        public string RegRutaImagen { get; set; }
        public string RegAnuncioEstado { get; set; }
        public Nullable<System.DateTime> RegAnuncioFecha { get; set; }
    }
}
