//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EncuestaEntities : DbContext
    {
        public EncuestaEntities()
            : base("name=EncuestaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adcompania> adcompania { get; set; }
        public virtual DbSet<adlocalidades> adlocalidades { get; set; }
        public virtual DbSet<adusuarionotificacion> adusuarionotificacion { get; set; }
        public virtual DbSet<adusuarios> adusuarios { get; set; }
        public virtual DbSet<adcompanialocalidad> adcompanialocalidad { get; set; }
        public virtual DbSet<adusuariolocalidad> adusuariolocalidad { get; set; }
        public virtual DbSet<adusuarioscompania> adusuarioscompania { get; set; }
        public virtual DbSet<adperfil> adperfil { get; set; }
        public virtual DbSet<adperfilmenu> adperfilmenu { get; set; }
        public virtual DbSet<adusuarioperfil> adusuarioperfil { get; set; }
        public virtual DbSet<admenu> admenu { get; set; }
        public virtual DbSet<admodulo> admodulo { get; set; }
        public virtual DbSet<adusuarioafiliado> adusuarioafiliado { get; set; }
        public virtual DbSet<PerfilDuo> PerfilDuo { get; set; }
        public virtual DbSet<Registrado> Registrado { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<AnuncioImages> AnuncioImages { get; set; }
        public virtual DbSet<Anuncio> Anuncio { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<works> works { get; set; }
    
        public virtual ObjectResult<spObtenerSolicitudAdmin_Result> spObtenerSolicitudAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerSolicitudAdmin_Result>("spObtenerSolicitudAdmin");
        }
    
        public virtual ObjectResult<spObtenerSolicitudGeneral_Result> spObtenerSolicitudGeneral(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerSolicitudGeneral_Result>("spObtenerSolicitudGeneral", usuarioParameter);
        }
    }
}
