//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrado
    {
        public int RegId { get; set; }
        public string RegCodigoUnico { get; set; }
        public string RegNombres { get; set; }
        public string RegApellidos { get; set; }
        public string RegNombreCompleto { get; set; }
        public string RegContrasenia { get; set; }
        public string RegEmail { get; set; }
        public string RegNumeroCelular { get; set; }
        public Nullable<System.DateTime> RegFecha { get; set; }
        public Nullable<int> AnioReg { get; set; }
        public Nullable<int> MesReg { get; set; }
        public Nullable<int> DiaReg { get; set; }
        public Nullable<bool> Tecnologia { get; set; }
        public Nullable<bool> Legales { get; set; }
        public Nullable<bool> Comunicacion { get; set; }
        public Nullable<bool> Comercio { get; set; }
        public Nullable<bool> ArteDiseno { get; set; }
        public Nullable<bool> ServiciosTecnicos { get; set; }
        public Nullable<bool> Urbanismo { get; set; }
        public Nullable<bool> Emprendimientos { get; set; }
    }
}
